import type { Metadata } from "next";
import localFont from "next/font/local";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { ModeToggle } from "@/components/mode-toggle";
import { Toaster } from "@/components/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Roboroomie Web App",
  description: "Generated by create next app",
};

  export default function Layout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
        >
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <SidebarProvider>
            <AppSidebar className="z-10"/>
            <SidebarInset className="h-full peer-data-[variant=inset]:min-h-[calc(100svh-theme(spacing.4))]">
              
            <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
          
            <Separator orientation="vertical" className="mr-2 h-4" />
            <div className="flex w-full items-center justify-between">
              <SidebarTrigger className="-ml-4" />
              <ModeToggle /> 
            </div>

              <Separator orientation="vertical" className="mr-2 h-4" />
              
            </header>
              <ScrollArea className="h-[calc(100svh-theme(spacing.4))]">
                <main className="">
                  {children}
                </main>
                <Toaster />
              </ScrollArea>
            </SidebarInset>
          </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    );
  }
  